name: k_project_v2.0.0
backend: ultralytics
version: 8.0.112
task: OBJECT_DETECTION
model_type: yolov8
model_size: x
categories:
-   category_id: 1
    supercategory: object
    name: nong
-   category_id: 2
    supercategory: object
    name: bess
-   category_id: 3
    supercategory: object
    name: sung
-   category_id: 4
    supercategory: object
    name: gangjunchi
-   category_id: 5
    supercategory: object
    name: bluegill
-   category_id: 6
    supercategory: object
    name: ing
-   category_id: 7
    supercategory: object
    name: bung
-   category_id: 8
    supercategory: object
    name: nuchi
