name: k_project_v1.0.0
backend: ultralytics
version: 8.0.112
task: OBJECT_DETECTION
model_type: yolov8
model_size: x
categories:
-   category_id: 1
    supercategory: object
    name: "\uB18D\uC5B4"
-   category_id: 2
    supercategory: object
    name: "\uBCA0\uC2A4"
-   category_id: 3
    supercategory: object
    name: "\uC22D\uC5B4"
-   category_id: 4
    supercategory: object
    name: "\uAC15\uC900\uCE58"
-   category_id: 5
    supercategory: object
    name: "\uBE14\uB8E8\uAE38"
-   category_id: 6
    supercategory: object
    name: "\uC789\uC5B4"
-   category_id: 7
    supercategory: object
    name: "\uBD95\uC5B4"
-   category_id: 8
    supercategory: object
    name: "\uB204\uCE58"
