dataset_path: c:\Users\admin\Desktop\Github\K-water_project\scripts\datasets\k_project_waffle_v1.0.0\exports\YOLO\data.yaml
epochs: 10
batch_size: 2
image_size:
- 640
- 640
learning_rate: 0.01
letter_box: true
pretrained_model: yolov8x.pt
device: '0'
workers: 2
seed: 0
advance_params: {}
verbose: true
